name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    name: Specs - Ruby ${{ matrix.ruby-version }} ${{matrix.gemfile}}
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 5e30c12a37d6500cfc4d084d0caafc530c404cbc3782c36207f420c3de1321ac
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      COVERAGE: true

    strategy:
      matrix:
        gemfile:
          - activerecord6
          - activerecord70
          - activerecord71
        ruby-version:
          - "3.2"
          - "3.1"
          - "3.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
        if: matrix.ruby-version == '3.2' && matrix.gemfile == 'activerecord71'
      - name: Run tests
        run: bundle exec rspec
      - name: Upload Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: matrix.ruby-version == '3.2' && matrix.gemfile == 'activerecord71'
